server:
  port: 8081
  servlet:
    context-path: /
spring:
  application:
    name: thereadingroom
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  sql:
    init:
      mode: always
      encoding: utf-8
  config:
    import: application-env.yml
logging:
  level:
    org:
      hibernate:
        SQL: debug
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs