server:
  port: 8081
spring:
  application:
    name: thereadingroom
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      mode: always
      encoding: utf-8
  config:
    import: application-env.yml
logging:
  level:
    org:
      hibernate:
        SQL: debug