openapi: 3.0.3
info:
  title: Your API Title
  description: Your API Description
  version: 1.0.0
servers:
  - url: http://localhost:8081
    description: Development server
paths:
  /api/books:
    get:
      tags:
        - Books
      operationId: getBooks
      summary: Get all books
      responses:
        '200':
          description: Successful response