openapi: 3.0.3
info:
  title: thereadingroom
  description: The only book store you need.
  version: 1.0.0
servers:
  - url: http://localhost:8081
    description: Development server
paths:
  /api/books:
    get:
      tags:
        - Books
      operationId: getBooks
      summary: Get all books
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
        '400':
          description: Not Found

  /api/store:
    get:
      tags:
        - Store
      operationId: viewStore
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ViewStore'
        '400':
          description: Not Found
components:
  schemas:
    ViewStore:
      type: object
      properties:
        id:
          type: integer