name: CI Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  build:
    name: Gradle Build
    runs-on: ubuntu-latest
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'gradle'

      - name: Print Environment Variables
        run: printenv | grep DB

      - name: List Configuration Files
        run: ls -R src/main/resources

      - name: Print Configuration File
        run: cat src/main/resources/application.yml

      - name: Setup Testcontainers Cloud Client
        uses: atomicjar/testcontainers-cloud-setup-action@v1
        with:
          token: ${{ secrets.TC_CLOUD_TOKEN }}
          
      - name: Check Docker Version
        run: docker --version
          
      - name: Build with Gradle
        run: ./gradlew build